apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
subjects:
- kind: ServiceAccount
  name: cloud-resource-operator
  namespace: cloud-resource-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
subjects:
- kind: ServiceAccount
  name: cloud-resource-operator
  namespace: cloud-resource-operator
  