# permissions for end users to edit postgressnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgressnapshot-editor-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - postgressnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - postgressnapshots/status
  verbs:
  - get
