# permissions for end users to view postgressnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgressnapshot-viewer-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - postgressnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - postgressnapshots/status
  verbs:
  - get
