apiVersion: integreatly.org/v1alpha1
kind: PostgresSnapshot
metadata:
  name: example-postgressnapshot
spec:
  # The postgres resource name for the snapshot you want to take
  resourceName: REPLACE_ME
